name: Build Feather Example Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle Executable
        run: chmod +x gradlew

      - name: Build Mod with Gradle
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Mod JAR
        uses: upload-artifact@v4
        with:
          name: feather-example-mod
          path: build/libs/*.jar
